### PR TITLE
Update base image

### PR DESCRIPTION
**Pull request by jakefhyde**
Updated alpine to `3.14.2`

### CODE REVIEW

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
Can you make the image locally and post the result of trivy scan?

**Comment by jakefhyde** [comment]
Command
-
`trivy i -s HIGH,CRITICAL rancher/backup-restore-operator:3f34a74-amd64`

Output
-
```
rancher/backup-restore-operator:3f34a74-amd64 (alpine 3.14.2)
=============================================================
Total: 0 (HIGH: 0, CRITICAL: 0)


usr/bin/backup-restore-operator (gobinary)
==========================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```

**Review by jiaqiluo — APPROVED** [review]

**Comment by jiaqiluo** [comment]
@jakefhyde  Can you backport this fix to the release/v1.0 branch?

**Review by nickgerace — APPROVED** [review]
LGTM to trivy scan.

**Comment by cbron** [comment]
We'll move this to SLE-BCI in long run, for now Jake is going to close as issue was fixed elsewhere.

**Pull request closed without merging**
