### PR TITLE
V2 Add ingress to networkpolicy allow all

### PR DESCRIPTION
**Pull request by r2ronoha**

### CODE REVIEW

**Comment by superseb** [comment]
This requires https://github.com/rancher/backup-restore-operator/pull/320 to be backported

**Comment by r2ronoha** [comment]
> This requires #320 to be backported

Do you know when that will be done?

**Comment by eliyamlevy** [comment]
@r2ronoha From what I know we're not cutting a new version of the release/v2.0 line this quarter. I can look into bringing this in for the next. Also if you would please write some context as to why you want this change (your pr) merged that would be great.

**Comment by r2ronoha** [comment]
> if you would please write some context as to why you want this change (your pr) merged that would be great.

The policy missing the `ingress` attribute blocks all ingress traffic, as opposed to allow (as the policy is intended to do). We are currently using a Kustomize override to add it, as it breaks access from the rest of the cluster to the resources in the namespace.

**Comment by r2ronoha** [comment]
> @r2ronoha From what I know we're not cutting a new version of the release/v2.0 line this quarter. I can look into bringing this in for the next. Also if you would please write some context as to why you want this change (your pr) merged that would be great.

This is still active. Waiting for release/v2.0 as per comment above

**Comment by eliyamlevy** [comment]
Hello, please work on getting the build to pass if you choose to develop it yourself.

**Comment by r2ronoha** [comment]
still relevant

**Comment by r2ronoha** [comment]
still relevant

**Comment by ericpromislow** [comment]
Could you rebase this PR off the `release/v4.0` branch.

And also please explain why this PR is needed, as there's no associated issue. 

What difference would I observe with this change in place, and how would I trigger it?

**Pull request closed without merging**
