### PR TITLE
Allow configurable resources

### PR DESCRIPTION
**Pull request by r2ronoha**

### CODE REVIEW

**Comment by r2ronoha** [comment]
This would be a nice to have. The pods were being killed by OOM in our cluster, and we had to implement a Kustomize override to increase the resources allocated to the deployment without affecting the default resources of the namespace

**Comment by eliyamlevy** [comment]
Build is failing, please resolve issues. I'd recommend just force pushing to the branch to have drone re-trigger the build

**Comment by eliyamlevy** [comment]
Hello, please submit an issue (link it if it exists) and work on getting the build to pass if you choose to develop it yourself.

**Comment by r2ronoha** [comment]
> Hello, please submit an issue (link it if it exists) and work on getting the build to pass if you choose to develop it yourself.

The failed checks seem to be related to [this comment](https://github.com/rancher/backup-restore-operator/pull/360#issuecomment-1561377819).

**Comment by r2ronoha** [comment]
still relevant

**Comment by r2ronoha** [comment]
still relevant

**Pull request closed without merging**
